### ISSUE TITLE
The Path™ to the beta release

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#32]
<a href="https://github.com/albireox"><img src="https://avatars.githubusercontent.com/u/568775?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [albireox](https://github.com/albireox)**
_Thursday Oct 06, 2016 at 21:47 GMT_
_Originally opened as https://github.com/marvin-manga/marvin/issues/67_

----

As we approach the beta release, here is a list of things that need to happen before we are ready to release:
- [x] - While we wait for the SDSS GitHub repo to be ready: **[this step can be skipped if the repo is available soon]**
  - [x] - Make marvin and marvin_brain public.
  - [x] - Using SubGit, sync sdss_access and tree and make them repos in marvin-manga. Make them public.
  - [x] - Make marvin_refactor the master branch. This will require tagging the current marvin/trunk as the last marvin 1, plus a number of module-related things in the sas-vm.
  - [x] - Move  sqlalchemy-boolean-search and wtforms-alchemy to marvin-manga.
  - [x] - Add tree, sdss_access, sqlalchemy-boolean-search, and wtforms-alchemy as external packages to marvin, using submodules.
  - [x] - Make sdss_access work without modules by defining the necessary environment variables that tree and `Path` need when marvin gets imported. Check that `sdss_sync` works.
  - [x] - Create setup.py for marvin.  Setup Travis-CI and Coveralls. 
  - [x] - Make marvin pip-installable.
  - [x] - Add pip-installable dependencies to setup.py. 
  - [x] - Tests in empty VM.
- [x] - Move all repos to the SDSS GitHub team, and make them public. Make sure all previous steps still work.
- [x] - Check Python 3 compatibility.
- [x] - Update documentation.
  - [x] - Add a `What's new?` and `Known Issues`. Reference them on the Marvin Web initial page.
  - [x] - Update tutorials.
- [x] - Tag a beta version.
- [x] - Put beta release on Zenodo. Add Zenodo DOI and Bibtex entry on Marvin Docs front page
- [x] - Check citations and acknowledgement instructions are ok in the Docs
- [x] - Update sas-vm nginx server
  - [x] - Keep Marvin 1 in one server pointing to the latest tag of Marvin 1.
  - [x] - Marvin 2 to point to the beta tag.
  - [x] - Add another nginx server running the master branch of Marvin 2.
- [x] - Celebrate.

**Comment by albireox** [comment]
<a href="https://github.com/albireox"><img src="https://avatars.githubusercontent.com/u/568775?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [albireox](https://github.com/albireox)**
_Thursday Oct 06, 2016 at 21:47 GMT_

----

Instead of commenting, just add/remove/modify/tick items in the original post.

**Comment by albireox** [comment]
It is with great please that I close this ticket.
