### ISSUE TITLE
List of tests that fail

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#467]
### Python 2.7
- [ ] misc/test_misc.py:20 TestMisc.test_custom_drpall[MPL-6-HYB10-GAU-MILESHC-8485-1901-MPL-6-MPL-4-v1_5_1]
- [ ] misc/test_misc.py:20 TestMisc.test_custom_drpall[MPL-6-SPX-GAU-MILESHC-8485-1901-MPL-6-MPL-4-v1_5_1]
- [ ] utils/test_general.py:230 TestSortDir.test_sort_dir_map[MPL-6-SPX-GAU-MILESHC-8485-1901-Map-expected0]
- [ ] utils/test_general.py:245 TestSortDir.test_sort_dir_spectrum[MPL-6-SPX-GAU-MILESHC-8485-1901-Spectrum-expected0]
- [ ] utils/test_general.py:230 TestSortDir.test_sort_dir_map[MPL-6-HYB10-GAU-MILESHC-8485-1901-Map-expected0]
- [ ] utils/test_general.py:245 TestSortDir.test_sort_dir_spectrum[MPL-6-HYB10-GAU-MILESHC-8485-1901-Spectrum-expected0]
- [ ] tools/test_query.py:99 TestQuerySearches.test_success_queries[MPL-6-remote-nodb-haflux]
- [ ] tools/test_query.py:99 TestQuerySearches.test_success_queries[MPL-6-remote-nodb-nsahaflux]
- [ ] tools/test_query.py:99 TestQuerySearches.test_success_queries[MPL-6-auto-nodb-haflux]
- [ ] tools/test_query.py:99 TestQuerySearches.test_success_queries[MPL-6-auto-nodb-nsahaflux]
- [ ] tools/test_query.py:157 TestQueryReturnParams.test_success[MPL-6-remote-nodb-rps2-nsa.z < 0.1]
- [ ] tools/test_query.py:157 TestQueryReturnParams.test_success[MPL-6-auto-nodb-rps2-nsa.z < 0.1]
- [ ] tools/test_query.py:240 TestQueryParams.test_getparams[MPL-6-remote-nodb-all]
- [ ] tools/test_query.py:240 TestQueryParams.test_getparams[MPL-6-auto-nodb-all]
- [ ] tools/test_results.py:70 TestResultsColumns.test_check_withadded[MPL-6-remote-nodb-colmns0-pars0-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:70 TestResultsColumns.test_check_withadded[MPL-6-auto-nodb-colmns0-pars0-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:82 TestResultsColumns.test_colnames[MPL-6-remote-nodb-nsa.z-z-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:82 TestResultsColumns.test_colnames[MPL-6-remote-nodb-cube.plateifu-plateifu-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:82 TestResultsColumns.test_colnames[MPL-6-remote-nodb-cube.mangaid-mangaid-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:82 TestResultsColumns.test_colnames[MPL-6-remote-nodb-spaxelprop.emline_gflux_ha_6564-haflux-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:82 TestResultsColumns.test_colnames[MPL-6-auto-nodb-nsa.z-z-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:82 TestResultsColumns.test_colnames[MPL-6-auto-nodb-cube.plateifu-plateifu-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:82 TestResultsColumns.test_colnames[MPL-6-auto-nodb-cube.mangaid-mangaid-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:82 TestResultsColumns.test_colnames[MPL-6-auto-nodb-spaxelprop.emline_gflux_ha_6564-haflux-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:193 TestResultsGetParams.test_get_list_all[MPL-6-remote-nodb-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:193 TestResultsGetParams.test_get_list_all[MPL-6-remote-nodb-haflux > 25]
- [ ] tools/test_results.py:193 TestResultsGetParams.test_get_list_all[MPL-6-auto-nodb-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:193 TestResultsGetParams.test_get_list_all[MPL-6-auto-nodb-haflux > 25]
- [ ] tools/test_results.py:369 TestResultsConvertTool.test_convert_success[MPL-6-remote-nodb-cube-Cube-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:369 TestResultsConvertTool.test_convert_success[MPL-6-remote-nodb-maps-Maps-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:369 TestResultsConvertTool.test_convert_success[MPL-6-remote-nodb-spaxel-Spaxel-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:369 TestResultsConvertTool.test_convert_success[MPL-6-remote-nodb-modelcube-ModelCube-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:369 TestResultsConvertTool.test_convert_success[MPL-6-auto-nodb-cube-Cube-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:369 TestResultsConvertTool.test_convert_success[MPL-6-auto-nodb-maps-Maps-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:369 TestResultsConvertTool.test_convert_success[MPL-6-auto-nodb-spaxel-Spaxel-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py:369 TestResultsConvertTool.test_convert_success[MPL-6-auto-nodb-modelcube-ModelCube-nsa.z < 0.1 and haflux > 25]
- [ ] web/test_webutils.py:28 TestBuildImageDict.test_realimages[MPL-6]
- [ ] tools/test_aperture.py:38 test_get_aperture[inputs0-outputs0]
- [ ] tools/test_aperture.py:38 test_get_aperture[inputs1-outputs1]
- [ ] tools/test_aperture.py:38 test_get_aperture[inputs2-outputs2]
- [ ] tools/test_aperture.py:38 test_get_aperture[inputs3-outputs3]
- [ ] tools/test_aperture.py:38 test_get_aperture[inputs4-outputs4]
- [ ] tools/test_aperture.py:38 test_get_aperture[inputs5-outputs5]
- [ ] tools/test_quantities.py:91 TestDataCube.test_snr
- [ ] tools/test_quantities.py:229 TestSpectrum.test_snr

### Python 3.5
- [ ] misc/test_misc.py TestMisc.test_custom_drpall[MPL-6-HYB10-GAU-MILESHC-8485-1901-MPL-6-MPL-4-v1_5_1]
- [ ] misc/test_misc.py TestMisc.test_custom_drpall[MPL-6-SPX-GAU-MILESHC-8485-1901-MPL-6-MPL-4-v1_5_1]
- [ ] tools/test_spaxel.py TestModelCubeGetSpaxel.test_getspaxel[api-MPL-6-SPX-GAU-MILESHC-8485-1901]
- [ ] tools/test_spaxel.py TestModelCubeGetSpaxel.test_getspaxel[api-MPL-6-HYB10-GAU-MILESHC-8485-1901]
- [ ] tools/test_modelcube.py TestModelCube.test_get_flux_db[MPL-6-SPX-GAU-MILESHC-8485-1901]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes0]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes2]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes3]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes5]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes6]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes8]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes9]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes11]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes12]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes14]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes15]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes17]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes18]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes20]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes21]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes23]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes24]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-SPX-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes26]
- [ ] tools/test_spaxel.py TestSpaxel.test_dir[MPL-6-SPX-GAU-MILESHC-8485-1901]
- [ ] tools/test_spaxel.py TestSpaxel.test_getattr[MPL-6-SPX-GAU-MILESHC-8485-1901]
- [ ] tools/test_spaxel.py TestSpaxel.test_force_load[MPL-6-SPX-GAU-MILESHC-8485-1901-models]
- [ ] tools/test_spaxel.py TestPickling.test_pickling_all_api[MPL-6-SPX-GAU-MILESHC-8485-1901]
- [ ] tools/test_spaxel.py TestMaskbit.test_quality_flags[MPL-6-SPX-GAU-MILESHC-8485-1901]
- [ ] tools/test_spaxel.py TestModelCubeGetSpaxel.test_getspaxel_db_api_model[MPL-6-SPX-GAU-MILESHC-8485-1901]
- [ ] tools/test_spaxel.py TestModelCubeGetSpaxel.test_getspaxel_matches_file_db_remote[MPL-6-SPX-GAU-MILESHC-8485-1901]
- [ ] utils/test_general.py TestSortDir.test_sort_dir_map[MPL-6-SPX-GAU-MILESHC-8485-1901-Map-expected0]
- [ ] utils/test_general.py TestSortDir.test_sort_dir_spectrum[MPL-6-SPX-GAU-MILESHC-8485-1901-Spectrum-expected0]
- [ ] tools/test_modelcube.py TestModelCube.test_get_flux_db[MPL-6-HYB10-GAU-MILESHC-8485-1901]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes0]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes2]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes3]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes5]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes6]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes8]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes9]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes11]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes12]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes14]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes15]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes17]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes18]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes20]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes21]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes23]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes24]
- [ ] tools/test_spaxel.py TestSpaxel.test_SpaxelBase[MPL-6-HYB10-GAU-MILESHC-8485-1901-cube_maps_modelcube_modes26]
- [ ] tools/test_spaxel.py TestSpaxel.test_dir[MPL-6-HYB10-GAU-MILESHC-8485-1901]
- [ ] tools/test_spaxel.py TestSpaxel.test_getattr[MPL-6-HYB10-GAU-MILESHC-8485-1901]
- [ ] tools/test_spaxel.py TestSpaxel.test_force_load[MPL-6-HYB10-GAU-MILESHC-8485-1901-models]
- [ ] tools/test_spaxel.py TestPickling.test_pickling_all_api[MPL-6-HYB10-GAU-MILESHC-8485-1901]
- [ ] tools/test_spaxel.py TestMaskbit.test_quality_flags[MPL-6-HYB10-GAU-MILESHC-8485-1901]
- [ ] tools/test_spaxel.py TestModelCubeGetSpaxel.test_getspaxel_db_api_model[MPL-6-HYB10-GAU-MILESHC-8485-1901]
- [ ] utils/test_general.py TestSortDir.test_sort_dir_map[MPL-6-HYB10-GAU-MILESHC-8485-1901-Map-expected0]
- [ ] utils/test_general.py TestSortDir.test_sort_dir_spectrum[MPL-6-HYB10-GAU-MILESHC-8485-1901-Spectrum-expected0]
- [ ] tools/test_query.py TestQuerySearches.test_success_queries[MPL-6-remote-nodb-haflux]
- [ ] tools/test_query.py TestQuerySearches.test_success_queries[MPL-6-remote-nodb-nsahaflux]
- [ ] tools/test_query.py TestQuerySearches.test_success_queries[MPL-6-auto-nodb-haflux]
- [ ] tools/test_query.py TestQuerySearches.test_success_queries[MPL-6-auto-nodb-nsahaflux]
- [ ] tools/test_query.py TestQueryReturnParams.test_success[MPL-6-remote-nodb-rps2-nsa.z < 0.1]
- [ ] tools/test_query.py TestQueryReturnParams.test_success[MPL-6-auto-nodb-rps2-nsa.z < 0.1]
- [ ] tools/test_query.py TestQueryParams.test_getparams[MPL-6-remote-nodb-all]
- [ ] tools/test_query.py TestQueryParams.test_getparams[MPL-6-auto-nodb-all]
- [ ] tools/test_results.py TestResultsColumns.test_check_withadded[MPL-6-remote-nodb-colmns0-pars0-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsColumns.test_check_withadded[MPL-6-auto-nodb-colmns0-pars0-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsColumns.test_colnames[MPL-6-remote-nodb-nsa.z-z-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsColumns.test_colnames[MPL-6-remote-nodb-cube.plateifu-plateifu-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsColumns.test_colnames[MPL-6-remote-nodb-cube.mangaid-mangaid-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsColumns.test_colnames[MPL-6-remote-nodb-spaxelprop.emline_gflux_ha_6564-haflux-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsColumns.test_colnames[MPL-6-auto-nodb-nsa.z-z-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsColumns.test_colnames[MPL-6-auto-nodb-cube.plateifu-plateifu-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsColumns.test_colnames[MPL-6-auto-nodb-cube.mangaid-mangaid-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsColumns.test_colnames[MPL-6-auto-nodb-spaxelprop.emline_gflux_ha_6564-haflux-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestMarvinTuple.test_create[MPL-6-remote-nodb]
- [ ] tools/test_results.py TestMarvinTuple.test_create[MPL-6-auto-nodb]
- [ ] tools/test_results.py TestMarvinTuple.test_add[MPL-6-remote-nodb]
- [ ] tools/test_results.py TestMarvinTuple.test_add[MPL-6-auto-nodb]
- [ ] tools/test_results.py TestResultsGetParams.test_get_list_all[MPL-6-remote-nodb-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsGetParams.test_get_list_all[MPL-6-remote-nodb-haflux > 25]
- [ ] tools/test_results.py TestResultsGetParams.test_get_list_all[MPL-6-auto-nodb-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsGetParams.test_get_list_all[MPL-6-auto-nodb-haflux > 25]
- [ ] tools/test_results.py TestResultsConvertTool.test_convert_success[MPL-6-remote-nodb-cube-Cube-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsConvertTool.test_convert_success[MPL-6-remote-nodb-maps-Maps-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsConvertTool.test_convert_success[MPL-6-remote-nodb-spaxel-Spaxel-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsConvertTool.test_convert_success[MPL-6-remote-nodb-modelcube-ModelCube-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsConvertTool.test_convert_success[MPL-6-auto-nodb-cube-Cube-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsConvertTool.test_convert_success[MPL-6-auto-nodb-maps-Maps-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsConvertTool.test_convert_success[MPL-6-auto-nodb-spaxel-Spaxel-nsa.z < 0.1 and haflux > 25]
- [ ] tools/test_results.py TestResultsConvertTool.test_convert_success[MPL-6-auto-nodb-modelcube-ModelCube-nsa.z < 0.1 and haflux > 25]
- [ ] web/test_webutils.py TestBuildImageDict.test_realimages[MPL-6]
- [ ] tools/test_aperture.py test_get_aperture[inputs0-outputs0]
- [ ] tools/test_aperture.py test_get_aperture[inputs1-outputs1]
- [ ] tools/test_aperture.py test_get_aperture[inputs2-outputs2]
- [ ] tools/test_aperture.py test_get_aperture[inputs3-outputs3]
- [ ] tools/test_aperture.py test_get_aperture[inputs4-outputs4]
- [ ] tools/test_aperture.py test_get_aperture[inputs5-outputs5]
- [ ] tools/test_spaxel.py TestBin.test_bad_binid
- [ ] tools/test_spaxel.py TestBin.test_load_all

### Python 3.6
- [ ] python/marvin/tests/misc/test_misc.py:20 TestMisc.test_custom_drpall[MPL-6-HYB10-GAU-MILESHC-8485-1901-MPL-6-MPL-4-v1_5_1]
- [ ] python/marvin/tests/misc/test_misc.py:20 TestMisc.test_custom_drpall[MPL-6-SPX-GAU-MILESHC-8485-1901-MPL-6-MPL-4-v1_5_1]
- [ ] python/marvin/tests/utils/test_general.py:230 TestSortDir.test_sort_dir_map[MPL-6-SPX-GAU-MILESHC-8485-1901-Map-expected0]
- [ ] python/marvin/tests/utils/test_general.py:245 TestSortDir.test_sort_dir_spectrum[MPL-6-SPX-GAU-MILESHC-8485-1901-Spectrum-expected0]
- [ ] python/marvin/tests/utils/test_general.py:230 TestSortDir.test_sort_dir_map[MPL-6-HYB10-GAU-MILESHC-8485-1901-Map-expected0]
- [ ] python/marvin/tests/utils/test_general.py:245 TestSortDir.test_sort_dir_spectrum[MPL-6-HYB10-GAU-MILESHC-8485-1901-Spectrum-expected0]
- [ ] python/marvin/tests/tools/test_query.py:240 TestQueryParams.test_getparams[MPL-6-remote-nodb-all]
- [ ] python/marvin/tests/tools/test_query.py:240 TestQueryParams.test_getparams[MPL-6-auto-nodb-all]
- [ ] python/marvin/tests/tools/test_results.py:96 TestMarvinTuple.test_create[MPL-6-remote-nodb]
- [ ] python/marvin/tests/tools/test_results.py:96 TestMarvinTuple.test_create[MPL-6-auto-nodb]
- [ ] python/marvin/tests/tools/test_results.py:108 TestMarvinTuple.test_add[MPL-6-remote-nodb]
- [ ] python/marvin/tests/tools/test_results.py:108 TestMarvinTuple.test_add[MPL-6-auto-nodb]
- [ ] python/marvin/tests/core/test_config.py:90 TestAccess.test_tree
- [ ] python/marvin/tests/tools/test_aperture.py:38 test_get_aperture[inputs0-outputs0]
- [ ] python/marvin/tests/tools/test_aperture.py:38 test_get_aperture[inputs1-outputs1]
- [ ] python/marvin/tests/tools/test_aperture.py:38 test_get_aperture[inputs2-outputs2]
- [ ] python/marvin/tests/tools/test_aperture.py:38 test_get_aperture[inputs3-outputs3]
- [ ] python/marvin/tests/tools/test_aperture.py:38 test_get_aperture[inputs4-outputs4]
- [ ] python/marvin/tests/tools/test_aperture.py:38 test_get_aperture[inputs5-outputs5]

**Comment by havok2063** [comment]
What branch are these on?

**Comment by albireox** [comment]
I think this is master. I may have compiled this from a different branch but most of the tests that fail are in places I haven't touched recently so I think those broken tests are general.

**Comment by havok2063** [comment]
Ok.  I'll take a look.  All the tests (no `--travis-subset` option) passed for me in 2.7 in the `dr15` branch before I merged.

**Comment by albireox** [comment]
The latest master 2.7 run has these tests failing

```
         - python/marvin/tests/utils/test_general.py:230 TestSortDir.test_sort_dir_map[MPL-6-SPX-GAU-MILESHC-8485-1901-Map-expected0]
         - python/marvin/tests/utils/test_general.py:230 TestSortDir.test_sort_dir_map[MPL-6-HYB10-GAU-MILESHC-8485-1901-Map-expected0]
         - python/marvin/tests/tools/test_aperture.py:38 test_get_aperture[inputs0-outputs0]
         - python/marvin/tests/tools/test_aperture.py:38 test_get_aperture[inputs1-outputs1]
         - python/marvin/tests/tools/test_aperture.py:38 test_get_aperture[inputs2-outputs2]
         - python/marvin/tests/tools/test_aperture.py:38 test_get_aperture[inputs3-outputs3]
         - python/marvin/tests/tools/test_aperture.py:38 test_get_aperture[inputs4-outputs4]
         - python/marvin/tests/tools/test_aperture.py:38 test_get_aperture[inputs5-outputs5]
```

so it could be something with my setup. The `test_aperture` failures are weird because they only happen sometime. I'll have to take a look.

**Comment by havok2063** [comment]
Ok, I'll check.  I'm sure after all the recent merges we've done into `master` things are broken again.
