### ISSUE TITLE
DR15 documentation

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#470]
Given that we are rewriting and restructuring the documentation in the `tools-doc-reorg` branch, I'm not adding documentation changes in new PRs, since they are merged to master and it would be easy for the documentation to get lost.

This is a list of things that need to be added directly to the `tools-doc-reorg` branch, specifically related to PRs / issues that are in progress or closed:

**Free floating**
- [X] #240 
- [x] #424
- [ ] Update the `visual guide` (wait until all new features have been implemented).
- [ ] `What's New` entry about the new authentication system and access modes.
- [ ] Update `Installation` with information about authentication, tokens, access modes, etc.

**PR #445**
- [x] Add entry to what's new.
- [ ] Update tutorials / examples to make use of the new kwargs.

**PR #449**
- [x] Add documentation on how to use `getAperture`.
- [x] Add an entry to what's new.

**PR #458**
- [ ] Make sure what's new entry makes it to the final version.

**PR #471**
- [x] Add an entry to what's new about the deredden ivar bug.

**PR #473**
- [ ] Document the new `RSS` and `RSSFiber` classes.
- [ ] Add/modify tutorials.
- [x] Add an entry to the what's new about the reimplementation of `RSS`.

**PR #516**
- [ ] Add what's new.
- [ ] Add documentation for new use of Bin.

**Comment by havok2063** [comment]
I think this can be effectively closed.
