### ISSUE TITLE
Check list for second round of vetting

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#500]
**Vetting version number:** 2.3.0-beta?
**Freezing date:** Aug 27?
**Vetting starts:** Sep 3?
**Vetting ends:** Sep 16?
**Everybody tries to crash Marvin day:** Sep 10?

## Software checklist
- [x] Has everything (MPL-4, MPL-5, MPL-6, MPL-7, DR15) been loaded to the DB?
- [x] Are the DR15 files accessible to rsync?
- [x] Are the DR15 file internally accessible so that the API server can use them?
- [x] Are the vetting version submodules set to the right commits?
- [x] Have we all signed off on this version?
   - [x] @havok2063 
   - [ ] @bretthandrews 
   - [ ] @albireox
   - [x] @margudo  
- [x] Is the vetting version tagged?
- [x] Is the vetting version released in PyPI?
- [x] Is the server running the right version of Marvin?
- [ ] Is the documentation correctly compiled and all plots show up in RTD?
- [ ] Are the Sentry problems solved (or Sentry disabled)?
- [ ] Has been Utah advertised of critical usage during the crash Marvin day? 

## Vetting preparation
- [x] Has the vetting group been identified?
- [x] Has the wiki page for the vetting been created?
- [x] Has a telecon with the vetting group been scheduled?
- [x] Have we created a vetting milestone for issues raised during the vetting?
- [x] Have we planned how to do the all-hands attack on Marvin?
- [x] Have we sent detailed instructions for the all-hands attack on Marvin?
- [x] Has the vetting group access to the public version?

## Vetting Groups and Items to Test
- [x] Web tester (public/collab)
- [ ] Tools tester (public/collab)
- [ ] Public User tester
- [ ] Collaboration User tester
- [x] Zero-day attack on Marvin
- [ ] Concurrent MPL-7 and DR15 data access
- [ ] Authentication and Access
- [ ] Documentation

**Comment by havok2063** [comment]
Release finished.  Closing.
