### ISSUE TITLE
DR15 Release Timeline

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#535]
Final DR15 timeline for Marvin from Anne-Marie.  

- [x] 12-Oct - start Marvin vetting
- [x] 29-Oct: finalise Marvin vetting
- [x] 29-Oct: prep public rsync server for DR15 (Joel)
- [x] 15-Nov: Marvin helpdesk training completed 
- [x] 24-Nov: Marvin finalised 
- [x] 03-Dec: Final checking of Marvin 
- [x] 10-Dec: DR15- make Marvin publicly visible 

TODOs
- [x] Finish VAC implementation (it's in the paper so we have to release it) #433 
- [ ] Fix slow spaxel slicing #525 
- [x] Critical bug fixes from Vetting (see vetting label)

**Comment by havok2063** [comment]
Release finished.  Closing.
